project_id = "ytjodudlnfamvnescumu"

[functions.create-super-admin]
verify_jwt = false

[functions.create-demo-accounts]
verify_jwt = false

[functions.whatsapp-inbound]
verify_jwt = false

[functions.get-student-report]
verify_jwt = false

[functions.whatsapp-outbound]
verify_jwt = true

[functions.permissions-api]
verify_jwt = true

[functions.surveys-api]
verify_jwt = true

[functions.virtual-classes-api]
verify_jwt = true

[functions.send-album-report]
verify_jwt = true

[functions.test-whatsapp]
verify_jwt = true

[functions.fix-whatsapp-templates]
verify_jwt = false