-- إضافة خطة تجريبية مجانية مع الميزات
INSERT INTO public.plans (id, name, name_ar, description, description_ar, price_monthly, price_quarterly, price_yearly, currency, max_students, max_teachers, max_classes, has_whatsapp, has_reports, has_analytics, storage_gb, features, is_active, is_popular, sort_order, created_at, updated_at)
VALUES (
    '10101010-1010-1010-1010-101010101010',
    'Demo Plan',
    'خطة تجريبية',
    'Full-featured demo plan for testing',
    'خطة تجريبية كاملة الميزات للاختبار',
    0,
    0,
    0,
    'SAR',
    100,
    10,
    10,
    true,
    true,
    true,
    50,
    '["student_management", "attendance_tracking", "reward_system", "whatsapp_integration", "media_sharing", "reports", "analytics", "multi_class", "unlimited_storage"]',
    true,
    false,
    0,
    now(),
    now()
) ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    name_ar = EXCLUDED.name_ar,
    description = EXCLUDED.description,
    description_ar = EXCLUDED.description_ar,
    max_students = EXCLUDED.max_students,
    max_teachers = EXCLUDED.max_teachers,
    max_classes = EXCLUDED.max_classes,
    has_whatsapp = EXCLUDED.has_whatsapp,
    has_reports = EXCLUDED.has_reports,
    has_analytics = EXCLUDED.has_analytics,
    storage_gb = EXCLUDED.storage_gb,
    features = EXCLUDED.features,
    updated_at = now();